name: 'Coverity scan and publish to Platform'
description: 'Performs a static code analysis using Coverity on Polaris and publishes detected issues to the CloudBees platform.'

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url: 
    description: Cloudbees API URL
    required: false
    default: "https://api.cloudbees.io"
  server-url: 
    description: 'Server URL'
    required: true
  api-token:  
    description: 'API token'
    required: true
  step-id:
    description: 'The ID of the step in the workflow'
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Create tar of source code
      shell: bash
      run: |
        tar -cvf output.tar .

    - name: Create request JSON file in workspace
      shell: bash
      run: |
        FILE_PATH="$GITHUB_WORKSPACE/store/request/request.json"
        mkdir -p "$(dirname "$FILE_PATH")"
        touch "$FILE_PATH"
        echo "File created at: $FILE_PATH"  

    - name: Generate reference files 
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e INPUT_CLOUDBEES_API_URL="${{ inputs.cloudbees-url }}" \
          -e INPUT_RUN_ID="${{ github.run_id }}" \
          -e INPUT_IS_GITHUB_WORKFLOW="true" \
          -e GITHUB_RUN_ID="${{ github.run_id }}" \
          -e GITHUB_WORKFLOW_REF="${{ github.workflow_ref }}" \
          -e GITHUB_RUN_ATTEMPT="${{ github.run_attempt }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_REF_NAME="${{ github.ref_name }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e GITHUB_JOB="${{ github.job }}" \
          -e GITHUB_PROVIDER="GITHUB" \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          -e ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN \
          -e ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL \
          public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:0dea78066b1aecbca8a3a6674aade8ee49b5d57a \
          generate-references --asset-type "CODE"

    - name: Print polaris conf
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          golang:latest \
          bash -c "chmod 777 $GITHUB_WORKSPACE/* && ls -al $GITHUB_WORKSPACE"

    - name: Run coverity on polaris compliance plugin
      shell: bash
      run: |
        docker run --rm \
          -u root \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e RUN_ID="${{ github.run_id }}" \
          -e JOB_ID="${{ github.job }}" \
          -e STEP_ID="${{ inputs.step-id }}" \
          -e POLARIS_SERVER_URL="${{ inputs.server-url }}" \
          -e POLARIS_ACCESS_TOKEN="${{ inputs.api-token }}" \
          public.ecr.aws/l7o7z1g8/actions/plugin-coverity-sca:daf06d0ba4087e173eb4af9483a29ac7aa569422 \
          --mode single
          
    - name: Complete execution plan
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e INPUT_CLOUDBEES_API_URL="${{ inputs.cloudbees-url }}" \
          -e INPUT_RUN_ID="${{ github.run_id }}" \
          -e INPUT_IS_GITHUB_WORKFLOW="true" \
          -e GITHUB_RUN_ID="${{ github.run_id }}" \
          -e GITHUB_WORKFLOW_REF="${{ github.workflow_ref }}" \
          -e GITHUB_RUN_ATTEMPT="${{ github.run_attempt }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_REF_NAME="${{ github.ref_name }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e GITHUB_JOB="${{ github.job }}" \
          -e GITHUB_PROVIDER="GITHUB" \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          -e ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN \
          -e ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL \
          public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:0dea78066b1aecbca8a3a6674aade8ee49b5d57a \
          process-outputs
